<!--楼层的主要内容的推荐商品或者拍品-->
<div class="gallery-main-list">
    <p class="gallery-main-title"><span>新近出版 / <a href="#">更多</a></span></p>
    <div class="gallery-main-product-xinshu clearfix" style="height: 486px;">
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide">
                <span class="gallery-book-list-img"><img src="../../../img/gallery/product_pic1.jpg" alt=""></span>
                <a href="" class="gallery-main-product-text" title="这里就是放一些文字这里就是放一些文字">这里就是放一些文字这里就是放一些文字</a>
                <p class="gallery-book-time">[美]保罗·沃尔克里</p>
                <p class="gallery-main-product-price"><i>￥150.00 </i><span>起</span></p>
        </span>
        <span class="gallery-lot-slide"></span>
        <span class="gallery-lot-slide"></span>
        <span class="gallery-lot-slide"></span>
        <span class="gallery-lot-slide"></span>
    </div>
</div>