<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>登录</title>
    <!-- build:head-css -->
    <!-- endbuild -->
</head>
<body class="login">
<div class="login_m">
    <div class="login_logo"><img src="/modules/admin/img/login/logo.png" width="200" height="55"></div>
    <div class="login_boder">
        <div class="login_padding">
            <h2>用户名</h2>
            <label>
                <input type="text" id="username" class="txt_input txt_input2" placeholder="Your name">
            </label>
            <h2>密码</h2>
            <label>
                <input type="password" name="textfield2" id="userpwd" class="txt_input" placeholder="Your Password">
            </label>
            <p class="forgot"><a href="javascript:void(0);">忘记密码?</a></p>
            <div class="rem_sub">
                <div class="rem_sub_l">
                    <input id="checkbox" type="checkbox" name="checkbox" id="save_me">
                    <label for="checkbox">记住</label>
                </div>
                <label>
                    <input type="button" class="sub_button" name="button" id="button" value="登录" style="opacity: 0.7;">
                </label>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<p align="center">&copy;kongfz.com</p>
<!-- build:footer-js -->
<!-- endbuild -->
</body>
</html>