<div class="footer_box">
    <div class="foot">
        <div class="footer_link text-center">
            <a href="<?= $site['www'] ?>help/aboutus.php">关于孔网</a><a href="<?= $site['www'] ?>help/lianxi.html">联系我们</a><a
                    href="<?= $site['help'] ?>">帮助中心</a><a href="<?= $site['www'] ?>help/copyright.php">版权隐私</a><a
                    href="<?= $site['www'] ?>help/guanggao.php">广告业务</a><a href="<?= $site['www'] ?>help/zhaopin.php">工作机会</a><a
                    href="<?= $site['m'] ?>">移动版</a>
        </div>
        <div class="text-center m_t25">
            <p>Copyright © 孔夫子旧书网  2002-<?= date('Y') ?> , All  Rights  Reserved </p>
            <p>京ICP证041501号<span class="m_r15 m_l15">|</span>海淀分局备案编号 1101082227<span class="m_r15 m_l15">|</span>出版经营许可证
            </p>
        </div>
    </div>
</div>