<!--楼层的推荐的书店或者拍卖专场-->
<div class="list-recommand-list">
    <p class="list-main-title"><span><?= $specialTitle ?> / <a href="<?= $specialMoreLink ?>">更多</a></span></p>
    <ul>
        <?php
        for ($i = 0; $i < count($specialId); $i++) { ?>
            <li>
                <div class="f_left"><span class="ico-small-box"></span></div>
                <div class="text_box"><a href="<?= $site['pm'] . 'special/' . $specialId[$i] ?>"
                                         class="list-recommand-list-name"><?= $specialName[$i] ?></a></div>
                <p class="list-recommand-list-intro"><?= $specialTime[$i] ?></p>
                <p class="list-shop-line"></p>
            </li>
            <?php
        }
        ?>
    </ul>
    <!--<div class="list-open-shop"><a href="#" class="list-open-shop-btn">我要开书店</a></div>-->
</div>
