<div class="xinshuLeftbar">
	<div class="border_box">			
			<!--分类-->
			<div class="fenlei_box">
				<h3>新书分类</h3>
				<ul class="list">
					<li><a href="#">小说</a></li>
					<li><a href="#">文学</a></li>
					<li><a href="#">历史</a></li>
					<li><a href="#">医学</a></li>
					<li><a href="#">天文</a></li>
					<li><a href="#">地理</a></li>
					<li><a href="#">历史</a></li>
					<li><a href="#">经济</a></li>
				</ul>
			</div>
			<!--畅销书店排行榜-->
			<div class="m_t50">
				<h3>畅销书店排行榜</h3>				
				<div class="change_text m_t10">
					<ul>
						<li><span class="w_num pull-left c_red">1.</span><span class="text_box"><a href="#">排行</a></span></li>
						<li><span class="w_num pull-left c_red">2.</span><span class="text_box"><a href="#">合众dfsd书局</a></span></li>
						<li><span class="w_num pull-left c_red">3.</span><span class="text_box"><a href="#">安徽芜湖万卷书屋</a></span></li>
						<li><span class="w_num pull-left">4.</span><span class="text_box"><a href="#">Dr.Jia 拥抱阳光</a></span></li>
						<li><span class="w_num pull-left">5.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">6.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">7.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">8.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">9.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">10.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">11.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">12.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">13.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">14.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">15.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">16.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">17.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">18.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">19.</span><span class="text_box"><a href="#">fsd书局</a></span></li>
						<li><span class="w_num pull-left">20.</span><span class="text_box"><a href="#">fsd书局</a></span></li>						
					</ul>
					
				</div>
			</div>
			
	
	</div>
	 <div class="change_fixed"></div>
</div>