<div class="cagetory-box">
	<div class="list-group">
		<div class="list-group-item item-header"  init-detail='wait' >
			<a href="#" class="title pull-left">图书分类</a>
			<a href="#" class="label pull-right">最新上书</a>
		</div>
		<div class="list-group-item item-remarkable"  init-detail='wait' >
			<div class="item-text">
				<a href="#" class="link">线装古籍</a>
				<a href="#" class="link">民国书刊</a>
			</div>
			<div class="detail">

			</div>
		</div>
		<div class="list-group-item item-remarkable"  init-detail='wait' >
			<div class="item-text">
				<a href="#" class="link">期刊</a>
				<a href="#" class="link">报纸 </a>
			</div>
			<div class="detail">
				
			</div>
		</div>
		<div class="list-group-item"  init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">小说</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">中国当代</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">科幻惊悚</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item"  init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">文学</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">中国当代</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">科幻惊悚</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item"  init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">历史</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">中国当代</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">科幻惊悚</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">国学古籍收藏</a>
					<a href="#" class="item-title">中国当代</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">科幻惊悚</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">艺术</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">超现实主义</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">人文社科</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">超现实主义</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">科技</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">超现实主义</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">科技</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">超现实主义</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<div class="text">
					<a href="#" class="title">科技</a>
					<a href="#" class="item-title">世界名著</a>
					<span class="split-line">|</span>
					<a href="#" class="item-title">超现实主义</a>
				</div>
				<div class="ico">&gt;</div>
			</div>
			<div class="detail">
					
			</div>
		</div>
	</div>
	<div class="list-group other">
		<div class="list-group-item item-header">
			<a href="#" class="title pull-left">艺术品分类</a>
		</div>
		<div class="list-group-item item-remarkable" init-detail='wait' >
			<div class="item-text">
				<a href="#" class="link">名人墨迹</a>
				<a href="#" class="link">名人字画</a>
			</div>
			<div class="detail">

			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<a href="#" class="link">连环画</a>
				<a href="#" class="link">版画宣传画</a>
			</div>
			<div class="detail">

			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<a href="#" class="link">碑帖印谱</a>
				<a href="#" class="link">照片影像</a>
			</div>
			<div class="detail">

			</div>
		</div>
		<div class="list-group-item" init-detail='wait' >
			<div class="item-text">
				<a href="#" class="link">邮票税票</a>
				<a href="#" class="link">古玩杂项</a>
			</div>
			<div class="detail">

			</div>
		</div>
	</div>
	<div class="split-block"></div>
	<div class="platform">
		<a href="#" class="item clearfix">
			<span class="ico pull-left">
				<span class="ico-box icon-zixun"></span>
			</span>
			<span class="text pull-right">
				<span class="title">资讯</span>
				<span class="lable">推广词推广词推广词推广词推广词</span>
			</span>
		</a>
		<a href="#" class="item clearfix">
			<span class="ico pull-left">
				<span class="ico-box icon-zixun"></span>
			</span>
			<span class="text pull-right">
				<span class="title">论坛</span>
				<span class="lable">推广词推广词推广词推广词推广词</span>
			</span>
		</a>
		<a href="#" class="item clearfix">
			<span class="ico pull-left">
				<span class="ico-box icon-zixun"></span>
			</span>
			<span class="text pull-right">
				<span class="title">书友古旧书交流</span>
				<span class="lable">预约电话：010-874365283</span>
			</span>
		</a>
	</div>
	<div class="other-info">
		<div class="help">
			<a href="#" class="header">
				<span class="ico pull-left">
					<span class="ico-box icon-wenhao"></span>
				</span>
				<span class="text">帮助中心</span>
			</a>
			<a href="#" class="header">
				<span class="ico pull-left">
					<span class="ico-box icon-kefu"></span>
				</span>
				<span class="text">在线客服留言<span class="label">（早8点-晚9点）</span></span>
			</a>
			<div class="list">
				<span class="ico pull-left">
					<span class="ico-box icon-dianhua"></span>
				</span>
				<div class="text">
					<div class="item">
						<div class="title">客服电话<span class="label">（早8点-晚9点）</span></div>
						<div class="phone">010-62620698&nbsp;&nbsp;&nbsp;&nbsp;010-64755951</div>
					</div>
					<div class="item">
						<div class="title">纠纷处理<span class="label">（早9点-晚6点）</span></div>
						<div class="phone">010-64726856</div>
					</div>
					<div class="item last">
						<div class="title">图书审核<span class="label">（早9点-晚6点）</span></div>
						<div class="phone">010-62620918</div>
					</div>
				</div>
			</div>
			<div class="list last">
				<span class="ico pull-left">
					<span class="ico-box icon-qq"></span>
				</span>
				<div class="text">
					<div class="item">
						<div class="title">客服QQ<span class="label">（早9点-晚6点）</span></div>
					</div>
				</div>
			</div>
		</div>
		<div class="disseminate clearfix">
			<div class="WeChat pull-left">
				<div class="header">关注孔网微信</div>
				<div class="code-qr">
					<img src="http://img.daimg.com/uploads/allimg/161101/3-161101160Z3.jpg" width="100%" height="100%" alt="关注孔网微信" />
				</div>
			</div>
			<div class="app pull-right"> 
				<div class="header">下载孔网APP</div>
				<div class="code-qr">
					<img src="http://img.daimg.com/uploads/allimg/161101/3-161101160Z3.jpg" width="100%" height="100%" alt="点击下载APP" />
				</div>
				<div class="title">iPhone | Android</div>
			</div>
		</div>
	</div>
</div>