<!--新书首页图书专题切换列表-->
 <div id="book_change_list" class="book_change_list m_t25">
     <!--标题-->
     <div class="book_big_box">
        <div class="xinshu_long_tit clearfix">
            <div class="pull-left tit_shop_left"><span class="red_border">专题</span><a href="#">西方摄影记者眼中的世界风云</a></div>
            <div class="pull-right tit_shop_name">来自：黄金书店书店</div>
        </div>    
        <div class="shoplist_box  clearfix">
            <div class="pull-right shop_name_box">
                   <div class="pd_box">
                       <p>黄金书店</p>
                       <p>信誉积分：6343</p>
                       <p>交易成功率：89%</p>
                       <p>好评率：98%</p>
                       <p class="m_t10"><a href="#" class="enter_shop">进店逛逛</a></p>
                    </div>
              </div>
             <ul class="clearfix text_box">
                <li class="pull-left shop_name_list ">
                    <a href="#" class="now bt">22222</a>
                    <a href="#" class="bt">克立兹 英语听力突破掌</a>
                    <a href="#" class="bt">gdfg克立兹 英sdfs突破掌</a>
                    <a href="#" class="bt">李阳.克立兹 英语听力突破掌</a>                    
                    <div class="page_box">
                        <span class="first_page">上一页</span>
                        <a href="javascript:;" class="up_page" style="display:none;">上一页</a>
                        <span><i>1</i>/<b>5</b></span>
                        <a href="javascript:;" class="next_page">下一页</a>
                        <span class="last_page" style="display:none;">下一页</span>
                    </div>
                </li>                
                <li class="text_box">
                    <div class="shop_book shop_book_item1">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">111</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item2" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">222</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item3" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">333</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item4" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">444</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                   
                </li>
            </ul>
            <ul class="clearfix text_box" style="display:none;">
                <li class="pull-left shop_name_list ">
                    <a href="#" class="now bt">2222破掌</a>
                    <a href="#" class="bt">克立兹 英语听力突破掌</a>
                    <a href="#" class="bt">gdfg克立兹 英sdfs突破掌</a>
                    <a href="#" class="bt">李阳.克立兹 英语听力突破掌</a>
                    <a href="#" class="bt last" style="display:none;">李阳.克立兹 英语听力突破掌</a>
                    <div class="page_box">
                        <span class="up_page">上一页</span>
                        <a href="javascript:;" class="up_page" style="display:none;">上一页</a>
                       <span>3/5</span>
                        <a href="javascript:;" class="next_page">下一页</a>
                        <span class="next_page" style="display:none;">下一页</span>
                    </div>
                </li>                
                <li class="text_box">
                    <div class="shop_book shop_book_item1">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">111</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item2" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">222</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item3" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">333</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item4" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">444</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                   
                </li>
            </ul>
            <ul class="clearfix text_box" style="display:none;">
                <li class="pull-left shop_name_list ">
                    <a href="#" class="now bt">333</a>
                    <a href="#" class="bt">克立兹 英语听力突破掌</a>
                    <a href="#" class="bt">gdfg克立兹 英sdfs突破掌</a>
                    <a href="#" class="bt">李阳.克立兹 英语听力突破掌</a>
                    <a href="#" class="bt last" style="display:none;">李阳.克立兹 英语听力突破掌</a>
                    <div class="page_box">
                        <span class="up_page">上一页</span>
                        <a href="javascript:;" class="up_page" style="display:none;">上一页</a>
                        <span>3/5</span>
                        <a href="javascript:;" class="next_page">下一页</a>
                        <span class="next_page" style="display:none;">下一页</span>
                    </div>
                </li>                
                <li class="text_box">
                    <div class="shop_book shop_book_item1">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">111</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item2" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">222</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item3" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">333</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                    <div class="shop_book shop_book_item4" style="display:none;">
                        <div class="shoplist_img_box">
                            <a href="#"><img src="/img/shop/test_img2.jpg"/></a>
                        </div>
                        <div class="shoplist_txt">
                            <p class="name_box"><a href="#">444</a></p>
                            <p class="m_t10">分类： 文学</p>
                            <p>品相：七五品</p>
                            <div class="price">¥150.00</div>
                        </div>
                    </div>
                   
                </li>
            </ul>
                       
        </div>
    </div>  
      
        <div class="text-center nomore_box">没有更多了</div>
    </div>
