<div class="content">
    <div class="friend_link_box">
        <div class="friend_link_tit clearfix">
            <a href="javascript:;" class="now">合作伙伴</a><a href="javascript:;">友情链接</a><a href="javascript:;">推荐专题</a>
        </div>
        <div class="friend_link_list clearfix m_t10">
            <div class="f_box" style="display:block;">
               <?php if (is_array($partners) && !empty($partners)) {
                    foreach ($partners as $item) {
                        ?>
                        <a href="<?= $item['linkUrl'] ?>" target="_blank" title=""><?= $item['linkName']?></a>
                    <?php }
                } ?>
            </div>
            <div class="f_box" style="display:none;">
                <?php if (is_array($friends) && !empty($friends)) {
                    foreach ($friends as $item) {
                        ?>
                        <a href="<?= $item['linkUrl'] ?>" target="_blank" title=""><?= $item['linkName']?></a>
                    <?php }
                } ?>
            </div>
            <div class="f_box" style="display:none;">
                <?php if (is_array($topics) && !empty($topics)) {
                    foreach ($topics as $item) {
                        ?>
                        <a href="<?= $item['linkUrl'] ?>" target="_blank" title=""><?= $item['linkName']?></a>
                    <?php }
                } ?>
            </div>
        </div>
    </div>
</div>
