<div class="zhuanti_list_box">
<div class="clearfix booklist_tit no_bor"> <h3>推荐专题</h3></div>
    <ul class="clearfix">
        <li>
            <a href="#">
            <div class="pic"><img src="/img/zhuanti/test_img1.jpg"/></div>
            <div class="txt_box">
                <div class="bt">这一百本书每本都值得买</div>
                <div class="info">
                    <p>他无以伦比的个人魅力和诗歌力量一百多年来的影响远远超出文字的界限。有三十三位世界艺术家，将他们从叶芝诗歌中读到的灵感，变成了炙热的视觉艺术</p>
                </div>
                <div class="info_more">查看详情</div>
            </div>
            </a>
        </li>
         <li>
            <a href="#">
            <div class="pic"><img src="/img/zhuanti/test_img1.jpg"/></div>
            <div class="txt_box">
                <div class="bt">这一百本书每本都值得买</div>
                <div class="info">
                    <p>他无以伦比的个人魅力和诗歌力量一百多年来的影响远远超出文字的界限。有三十三位世界艺术家，将他们从叶芝诗歌中读到的灵感，变成了炙热的视觉艺术</p>
                </div>
                <div class="info_more">查看详情</div>
            </div>
            </a>
        </li>
         <li>
            <a href="#">
            <div class="pic"><img src="/img/zhuanti/test_img1.jpg"/></div>
            <div class="txt_box">
                <div class="bt">这一百本书每本都值得买</div>
                <div class="info">
                    <p>他无以伦比的个人魅力和诗歌力量一百多年来的影响远远超出文字的界限。有三十三位世界艺术家，将他们从叶芝诗歌中读到的灵感，变成了炙热的视觉艺术</p>
                </div>
                <div class="info_more">查看详情</div>
            </div>
            </a>
        </li>
        <li>
            <a href="#">
            <div class="pic"><img src="/img/zhuanti/test_img1.jpg"/></div>
            <div class="txt_box">
                <div class="bt">这一百本书每本都值得买</div>
                <div class="info">
                    <p>他无以伦比的个人魅力和诗歌力量一百多年来的影响远远超出文字的界限。有三十三位世界艺术家，将他们从叶芝诗歌中读到的灵感，变成了炙热的视觉艺术</p>
                </div>
                <div class="info_more">查看详情</div>
            </div>
            </a>
        </li>
        <li>
            <a href="#">
            <div class="pic"><img src="/img/zhuanti/test_img1.jpg"/></div>
            <div class="txt_box">
                <div class="bt">这一百本书每本都值得买</div>
                <div class="info">
                    <p>他无以伦比的个人魅力和诗歌力量一百多年来的影响远远超出文字的界限。有三十三位世界艺术家，将他们从叶芝诗歌中读到的灵感，变成了炙热的视觉艺术</p>
                </div>
                <div class="info_more">查看详情</div>
            </div>
            </a>
        </li>
         <li>
            <a href="#">
            <div class="pic"><img src="/img/zhuanti/test_img1.jpg"/></div>
            <div class="txt_box">
                <div class="bt">这一百本书每本都值得买</div>
                <div class="info">
                    <p>他无以伦比的个人魅力和诗歌力量一百多年来的影响远远超出文字的界限。有三十三位世界艺术家，将他们从叶芝诗歌中读到的灵感，变成了炙热的视觉艺术</p>
                </div>
                <div class="info_more">查看详情</div>
            </div>
            </a>
        </li>
    </ul>    
<div class="page_box ">
    <div class="box_border clearfix">
    <span><</span>    
    <a href="javascript:;" style="display:none;"><</a>
    <a href="javascript:;" class="now">1</a>    
    <a href="javascript:;">2</a>
    <a href="javascript:;">3</a>
    <a href="javascript:;">4</a>
    <span>···</span>
    <a href="javascript:;">></a>
    <span style="display:none;">></span>    
    </div>
</div>
</div>
 