<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>运营后台</title>
    <!-- build:head-css -->
    <!-- endbuild -->
</head>
<body>
   <div id="wrapper">
       <!-- Navigation -->
       <?php include APP_PATH . '/application/modules/Admin/views/common/nav.phtml'?>

   </div>
   <div id="page-wrapper">
       <div class="easyui-tabs" style="width:100%;height:auto">
           <div title="主页" style="padding:10px">
               <p>欢迎……</p>
               <p>您上次登录的ip是127.0.0.1，时间为2016-12-21 12:12:00，您总共登录了123次.</p>
               <input  id="dd"  type= "text" class= "easyui-datebox" required ="required"> </input>
           </div>
       </div>
   </div>
<!-- build:footer-js -->
<!-- endbuild -->
</body>
</html>