
<div class="head">
    <div class="clearfix nav_box">
        <ul class="f_left left_part">
            <li><a href="#">首页</a></li>
            <li><a href="#">旧书</a></li>
            <li><a href="#">新书</a></li>
            <li class="line_right"></li>
        </ul>
        <ul class="f_left right_part">
            <li><a href="#"><span class="shu1 f_left m_r5 m_t22"></span>在线拍卖</a></li>
            <li><a href="#"><span class="shu2 f_left m_r5 m_t22"></span>艺术品专场</a></li>
        </ul>
    </div>
</div>