<div id="moduleId_<?= $parentId ?>" class=" ancient-box">
    <div class="ancient-title">
        <!--楼层的大标题名称和链接-->
        <div class="floor-big-title clearfix">
            <ul>
                <span class="floor-big-title-name"><?= $mainTitle ?></span>
                <li><a href="#">某大卖家某大卖家1</a></li>
                <li><a href="#">某大卖某大家2</a></li>
                <li><a href="#">某大卖家s3</a></li>
                <li><a href="#">某大ss卖家4</a></li>
                <li><a href="#">某大卖家5</a></li>
                <li><a href="#">某大sss卖家6</a></li>
                <li><a href="#">某大卖ss家7</a></li>
                <li><a href="#">某大卖ssss家8</a></li>
            </ul>
        </div>
    </div>
    <div class="ancient-left">
        @@include('widgets/gallery/lot/gallery.phtml')
    </div>
    <div class="ancient-right">
        @@include('widgets/list/art/list.phtml')
    </div>
    <div style="clear:both;"></div>
    <?php if(isset($tonglan) && is_array($tonglan)) { ?>
    <div class="ancient-ad">
        <div class="ancient-ad">
            <!--楼层的底部的广告位-->
            <div class="content floor-ad"><a href="<?php echo $tonglan['linkUrl']; ?>"><img src="<?php echo $tonglan['prefix'].$tonglan['imgUrl']; ?>" alt="<?php echo $tonglan['firstDesc']; ?>"></a></div>
        </div>
    </div>
    <?php } ?>
</div>
