<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;">
    <div class="navbar-header" style="position:relative;">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/admin/index/index">孔夫子运营后台</a>
        <!--<ul class="nav navbar-top-links navbar-right" style="position:absolute;right: -158px;top: 0px;">
            <li class="dropdown">
                <a class="dropdown-toggle admin-side-toggle" data-toggle="dropdown" href="javascript:;">
                    <i class="fa fa-exchange fa-fw"></i>
                </a>
            </li>
        </ul>-->
    </div>

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="/admin/index/index"><i class="fa fa-dashboard fa-fw"></i>运营后台</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>首页模块<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#"></i>轮播图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/bannerIndex">轮播图</a></li>
                                <li><a href="/admin/index/bannerModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>广告位区<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/advertisementIndex">广告位区</a></li>
                                <li><a href="/admin/index/advertisementModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>好书推荐<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/haoshuTuijianIsbn">ISBN池子</a></li>
                                <li><a href="/admin/index/haoshuTuijianModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>三张广告图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/zhuantiIndex">三张广告图</a></li>
                                <li><a href="/admin/index/zhuantiModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>通栏广告图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/tonglanIndex">通栏广告图</a></li>
                                <li><a href="/admin/index/tonglanModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>旧书<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/jiushuIndex">URL池子</a></li>
                                <li><a href="/admin/index/jiushuIsbn">ISBN池子</a></li>
                                <li><a href="/admin/index/jiushuRpond">右侧书店池子</a></li>
                                <li><a href="/admin/index/jiushuModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>新书<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/xinshuIndex">URL池子</a></li>
                                <li><a href="/admin/index/xinshuIsbn">ISBN池子</a></li>
                                <li><a href="/admin/index/xinshuRpond">右侧ISBN池子</a></li>
                                <li><a href="/admin/index/xinshuModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>民国书刊<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/periodicalIndex">拍主池子</a></li>
                                <li><a href="/admin/index/periodicalAuction">主栏拍品池子</a></li>
                                <li><a href="/admin/index/periodicalRpond">右侧书店池子</a></li>
                                <li><a href="/admin/index/periodicalModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>古籍<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/ancientIndex">拍主池子</a></li>
                                <li><a href="/admin/index/ancientAuction">主栏拍品池子</a></li>
                                <li><a href="/admin/index/ancientRpond">右侧书店池子</a></li>
                                <li><a href="/admin/index/ancientModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>艺术品<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/index/artworkAuction">主栏拍品池子</a></li>
                                <li><a href="/admin/index/artworkModule">模块设置</a></li>
                            </ul>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-book fa-fw"></i>书店首页模块<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#"></i>轮播图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/shop/bannerIndex">轮播图</a></li>
                                <li><a href="/admin/shop/bannerModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>单张广告图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/shop/singleIndex">单张广告图</a></li>
                                <li><a href="/admin/shop/singleModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>特色推荐<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/shop/teseTuiJianIndex">商品池子</a></li>
                                <li><a href="/admin/shop/teseTuiJianModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>超值低价<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/shop/dijiaIndex">商品池子</a></li>
                                <li><a href="/admin/shop/dijiaModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>旧书店有故事<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/shop/oldShopWithStoryIndex">书店池子</a></li>
                                <li><a href="/admin/shop/oldShopWithStoryModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>手快有 手慢无<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/shop/kuaiYouManWuIndex">ISBN池子</a></li>
                                <li><a href="/admin/shop/kuaiYouManWuModule">模块设置</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bookmark fa-fw"></i>新书首页模块<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#"></i>轮播图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/xinshu/bannerIndex">轮播图</a></li>
                                <li><a href="/admin/xinshu/bannerModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>单张广告图<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/xinshu/singleIndex">单张广告图</a></li>
                                <li><a href="/admin/xinshu/singleModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>推荐专题<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/xinshu/tuiJianZhuanTiIndex">推荐专题</a></li>
                                <li><a href="/admin/xinshu/tuiJianZhuanTiModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>低价促销<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/xinshu/diJiaCuXiaoModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>近期出版<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/xinshu/jinqiChubanIndex">ISBN池子</a></li>
                                <li><a href="/admin/xinshu/jinqiChubanModule">模块设置</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"></i>新书热卖榜<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li><a href="/admin/xinshu/xinshuRexiaoIndex">ISBN池子</a></li>
                                <li><a href="/admin/xinshu/xinshuRexiaoModule">模块设置</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>